### ISSUE TITLE
The organisation domain should be configurable in the config.json file

### ISSUE THREAD

**Issue by xrigau** [novoda/peepz#1]
I'm talking about this https://github.com/novoda/peepz/blob/54df28ca6b59b6ee8c46d6ffcef4d65c9c4c3b8f/web/dist/database.rules.json#L4

**Comment by ouchadam** [comment]
would probably be simpler to provide a sample and replace the file. We can't do too much with this file since it's firebase config

**Comment by ouchadam** [comment]
the hardcoded novoda domain in the database rules is a temporary step until teams/rooms are implemented 👍 so this will be gone at some point!
