### ISSUE TITLE
Sorting Peepz

### ISSUE THREAD

**Issue by tasomaniac** [novoda/peepz#12]
Peepz should be sorted. It can also be configurable ot support different sorting options.

**Comment by florianmski** [comment]
What would you sort by? I agree for the filtering one, I'm not sure about this one.
I feel like we should enforce defaults as much as possible, it should be just a wall of heads not a configuration nightmare :D

**Comment by tasomaniac** [comment]
Oh I opened this to discuss. Sorting right now is a problem. It should sort. Probably by date time. 

Configuration is not really necessary. I just wanted to fill the description. It's just an option.

**Comment by ouchadam** [comment]
currently we have a timestamp of when the current photo was taken and the webclient updates a `lastSeen` timestamp every 5 minutes.

At the moment the `lastSeen` is used to determine how grey a user is but this can definitely be used for filtering/sorting. We just need to decide how!

**Comment by tasomaniac** [comment]
I think configuration is not necessary but I would definitely sort by lastSeen.

**Comment by alexstyl** [comment]
What value does sorting give though? Is the order the true problem here?

**Comment by zegnus** [comment]
To me the problem is seeing people that doesn't match a reasonable time span, that leads to see people that's on holidays, or people repeated cross different screenshots as the screenshots are not being updated for a long time.

In order to sort this we can do two things:
- Remove everyone from the screen that hasn't update its image for more that 4h. That is twice a working day.
<and or>
- Sort by lastSeen so everyone not being updated falls to the bottom of the screen.

**Comment by ataulm** [comment]
@alexstyl if we order by last seen, you can resize the window so people are bigger without cutting off people (below the fold) who are active, nor wasting space (:grin:) on people who aren't.

**Comment by ataulm** [comment]
I added web because android already has this 😎

**Comment by alexstyl** [comment]
I agree with @zegnus 

I'd say let's kick people that are not active after x amount of time.
It's not a photo sharing service, right? It's about seeing who is on the other side. If the person is not on the other side, why bother showing them? 😄

**Comment by ouchadam** [comment]
let's start with hiding people after `X` amount of time and see if sorting is still needed after that?

How long are we thinking? 1 day?

**Comment by ataulm** [comment]
hiding has layout (design) implications, auto sorting doesn't

**Comment by zegnus** [comment]
@ouchadam 4h, we can increase if we feel that we need to

**Comment by ouchadam** [comment]
@ataulm I was seeing it more as `filtering` rather than dynamic hiding.

Anyone with a `lastSeen` of more than 4 hours doesn't make it to the wall?

**Comment by zegnus** [comment]
@ouchadam yeah, thanks! :)

**Comment by ataulm** [comment]
the sorting has been done on android/web.

there's other issues open for the other things.
