### ISSUE TITLE
Toggle to remove inactive people

### ISSUE THREAD

**Issue by zegnus** [novoda/peepz#31]
Add a toggle for allowing the client to remove inactive people

**Comment by ataulm** [comment]
🚢

**Comment by tasomaniac** [comment]
Just a small ranting on this. Every morning my `peepz` stops working after coming back from sleep. I refresh the page and this setting is reset on every refresh.

**Comment by ouchadam** [comment]
soon this will be synced to firebase! 

At the moment only the selected camera mode is synced

**Comment by tasomaniac** [comment]
That's cool 😎
